services:
  - type: web
    name: kahoot-bot-flooder
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PASSWORD
        sync: false
      - key: NODE_ENV
        value: production

